ifndef XILINX_SDX
$(error Environment variable XILINX_SDX is required and should point to SDAccel install area)
endif

SDA_FLOW = cpu_emu
HOST_SRCS = hamming.cpp xcl.cpp
HOST_EXE_DIR=.
HOST_EXE = vadd
HOST_CFLAGS = -g -Wall -DFPGA_DEVICE -DC_KERNEL
HOST_LFLAGS = 

KERNEL_SRCS = hamming_dist.cl
KERNEL_NAME = hamming_dist
KERNEL_DEFS = 
KERNEL_INCS = 

#set target device for XCLBIN
XDEVICE_REPO_PATH=/homes/fporrmann/workspace/
#XDEVICE=xilinx:adm-pcie-7v3:1ddr:3.0
XDEVICE=Bielefeld-University:raptor-dbv7-690t:DB-V7:0.0
#XDEVICE=Bielefeld-University:vc709:DB-V7:0.0
KEEP_TEMP=1
KERNEL_DEBUG=
XCLBIN_NAME=bin_hamming_dist
HOST_CFLAGS+=-DTARGET_DEVICE=\"${XDEVICE}\"
#BOARD_SETUP_FILE needs to point to setup.sh generated by xbinst command
BOARD_SETUP_FILE=setup.sh

ifeq (${SDA_FLOW},cpu_emu)
    CLCC_OPT += -t sw_emu
    XCLBIN = ${XCLBIN_NAME}_cpu_emu.xclbin
else ifeq (${SDA_FLOW},hw_emu)
    CLCC_OPT += -t hw_emu
    XCLBIN = ${XCLBIN_NAME}_hw_emu.xclbin
else ifeq (${SDA_FLOW},hw)
    XCLBIN = ${XCLBIN_NAME}_hw.xclbin
    CLCC_OPT += -t hw
endif

HOST_ARGS = ${XCLBIN}

COMMON_DIR = ../../common
include ${COMMON_DIR}/common.mk

